import 'dart:convert';

class Product {
  //Generated by Firebase DB
  String id;

  String name;
  String description;
  double price;
  int quantity;

  List<String> imagesUrl = [];
  String mainImageUrl;

  Product({
    this.name,
    this.description,
    this.price,
    this.quantity,
  });

  addImage(String url) {
    this.imagesUrl.add(url);
  }

  removeImage(String url) {
    this.imagesUrl.remove(url);
  }

  setMainImage(String url) {
    this.mainImageUrl = url;
  }

  String toJson() {
    Map<String, dynamic> productMap = {};
    productMap.putIfAbsent('id', () => id);
    productMap.putIfAbsent('name', () => name);
    productMap.putIfAbsent('quantity', () => quantity);
    productMap.putIfAbsent('description', () => description);
    productMap.putIfAbsent('price', () => price.toStringAsFixed(2));
    productMap.putIfAbsent('imagesUrl', () => imagesUrl);
    productMap.putIfAbsent('mainImageUrl', () => mainImageUrl);
    return json.encode(productMap);
  }

  Product.fromJson(String productJSON) {
    Map<String, dynamic> productMap = json.decode(productJSON);
    this.id = productMap['id'];
    this.name = productMap['name'];
    this.quantity = productMap['quantity'];
    this.description = productMap['description'];
    this.price = double.tryParse(productMap['price']);
    this.imagesUrl =
        List<String>.from(productMap['imagesUrl'] as List<dynamic>);
    this.mainImageUrl = productMap['mainImageUrl'];
  }
}
